Repository Daniel-Boll/axum-js, pull requests merged in 2023-10, with the labels that each got.

#2 Implement simple api example
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Cargo.toml
  LICENSE
  README.md
  STYLE_GUIDE.md
  __test__/index.spec.mjs
  build.rs
  index.d.ts
  index.js
  package.json
  rustfmt.toml
  src/application/app.rs
  src/application/mod.rs
  src/lib.rs
  src/utils/mod.rs
  src/utils/version.rs
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#12 Extend get method to support callbacks
  .github/FUNDING.yml
  Cargo.toml
  index.d.ts
  index.js
  package.json
  src/application/app.rs
  src/application/mod.rs
  src/application/request.rs
  src/application/response.rs
Labels: hacktoberfest-accepted, implementation

#13 Separate tests and CI into different workflows
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: hacktoberfest-accepted

#14 Update README.md
  README.md
Labels: hacktoberfest-accepted

#15 Issue Tracker Workflow
  .github/workflows/dependency-tracker.yml
Labels: enhancement, hacktoberfest-accepted

#17 Implement Additional HTTP Methods
  base.ts
  index.d.ts
  index.js
  package.json
  src/application/app.rs
  src/application/request.rs
  src/application/response.rs
  yarn.lock
Labels: enhancement, hacktoberfest-accepted, implementation
